import os
from time import ctime

i = 0

def sort_files(files, files_dates):
    j = h = 0
    files_and_dates = []
    dates = []
    for file in files:
        files_and_dates.append(f"{file}-{files_dates[j]}")
        j+=1

    dates.append([int(float(f.split("-")[-1])) for f in files_and_dates])

    sorted_dates = sorted(dates[0])

def add_desc():
    paths = list()
    for path in os.listdir("./"):
        if path != "sort.py":
            if os.path.isdir(path):
                for subpath in os.listdir(f"./{path}/"):
                    if subpath.split(".")[-1] == "py":
                        paths.append(f"./{path}/{subpath}")

    for path in paths:
        with open(path, "r+") as f:
            content = f.read()
            if not "DESCRIPTION:" in content:
                desc = input(f"{path} description:\n").split("\\")
                f.seek(0, 0)
                f.write("'''\nDESCRIPTION:\n")
                for line in desc:
                    f.writelines(f"    {line}\n")
                f.write(f"\nGenerated by \"sort.py\"\n'''\n\n{content}")
