'''
DESCRIPTION:
    Snake in the console with ASCII characters

Generated by "sort.py"
'''

from time import sleep
from random import randint
import keyboard
import os

toprint = ""
player_pos = player_pos_fixed = pos_to_go = 0
wid = 50
hei = 25
circle_radius = 4


def move(x, y):
    global player_pos, player_pos_fixed, pos_to_go, wid, hei
    if x != 0 and y == 0:
        # if player_pos_fixed in [k*hei+1 for k in range(wid)]:
        #     where = -wid
        # else:
        where = x
    elif x == 0 and y != 0:
        if y == abs(y):
            where = wid
        else:
            where = -wid

    else:
        where = 0

    toprint = ""
    xlabel = list()
    pos_to_go += where
    pos_to_go_fixed = pos_to_go
    player_pos = 0
    player_pos_fixed = player_pos

    if pos_to_go > hei*wid or pos_to_go <= 0:
        pos_to_go = player_pos

    for i in range(hei):
        for j in range(wid):
            player_pos += 1
            if player_pos == pos_to_go:
                player_pos_fixed = player_pos
                toprint += "██ "
            else:
                toprint += "   "

        toprint += f" {format(i+1, '02d')}\n\n"

    for i in range(wid):
        xlabel.append(format(i+1, '02d'))

    toprint += ' '.join(xlabel) + "\n"
    toprint += f"{player_pos_fixed}, {pos_to_go_fixed}"

    print(toprint)
    # print([i*hei for i in range(wid)])


def n_to_xy(n):
    global hei, wid


os.system("clear")
move(0, 0)

# while True:
#     sleep(0.01)
#     if keyboard.is_pressed("w"):
#         print()
#         os.system("clear")
#         move(0, -1)
#     elif keyboard.is_pressed("a"):
#         print()
#         os.system("clear")
#         move(-1, 0)
#     elif keyboard.is_pressed("s"):
#         print()
#         os.system("clear")
#         move(0, 1)
#     elif keyboard.is_pressed("d"):
#         print()
#         os.system("clear")
#         move(1, 0)
