'''
DESCRIPTION:
    Calculate probabilities of things happening (mostly with the random module)

Generated by "sort.py"
'''

from random import choice, randint, random
from matplotlib import pyplot as plt
from datetime import datetime as dtime
from time import time, sleep
from numpy import prod
import json


f = open("./proba/proba.json")
jso = json.load(f)

i = 0
heads = 0
tails = 0
heads_final = 0
tails_final = 0
three_times = 0
executed = 0
over_under_10 = 0
over_under_20 = 0
over_under_30 = 0
initial_time = str(dtime.now()).split(":")
initial_time_min = str(dtime.now()).split(":")[-2]
initial_time_sec = str(dtime.now()).split(":")[-1]
initial_time_hour = list(str(dtime.now()).split(
    ":")[-3])[-2]+list(str(dtime.now()).split(":")[-3])[-1]

try:
    n = int(input("number of time:\n"))
except:
    print("\n")
    exit()

try:
    while True:
        executed += 1
        three_times += 1
        heads = 0
        tails = 0
        for r in range(n):
            i += 1
            cf = ["heads", "tails"]
            random_ = cf[randint(0, len(cf)-1)]

            if random_ == "heads":
                heads += 1
                print("heads "+str(heads), end="\r")

            else:
                tails += 1
                print("tails "+str(tails), end="\r")

        tails_final += tails
        heads_final += heads

        proba_tails = tails/n*100
        if three_times >= 3:
            three_times = 0
            jso["results_tails"].append(str(proba_tails))


except KeyboardInterrupt:
    with open("./proba/proba.json", "w") as f:
        json.dump(jso, f)

    p_tails = tails_final/(executed*n)*100
    p_heads = heads_final/(executed*n)*100

    valst = []

    for item, value in jso.items():
        valst = [int(item) for item in value]
        print(sum(valst))
        print(len(value))

    print("\n\nresults:\ntails: "+str(tails_final)+" ("+str(p_tails)+"%)\n" +
          "heads: "+str(heads_final) +
          " ("+str(p_heads)+"%)\n"
          "("+str(p_tails+p_heads)+")\n"
          "tries: "+str(executed)+" (total "+str(i)+"), missing "+str(executed*n-i)+"\n")
    # "in "+str(dtime.now())-str(initial_time))
    plt.plot([1, 100])
    # plt.show()

    exit()
