'''
DESCRIPTION:
    I am trying to simulate gravity in the terminal by
    calculating the time it takes for an
    object to fall 1 meter / character.

Generated by "sort.py"
'''

import math
import matplotlib.pyplot as plt
from time import sleep, time

initial_pos = 100
gravity = 9.81
times = []
times_total = []


# def fall():
# global initial_pos, times
i = 0
time_to_sleep = 1
for i in range(initial_pos):
    im1 = i

    time_to_sleep = lambda z0: math.sqrt(2*(z0 - i)/9.81)
    if time_to_sleep(initial_pos) == 0: break

    if time_to_sleep(initial_pos) == 0:
        break

    tts = time_to_sleep(initial_pos)-time_to_sleep(initial_pos-1)
    times.append(f"{i}. {round(tts, 3)}")
    times_total.append(tts)
    
    # print(format(i+1, f'0{len(str(initial_pos))}d'))

    # if tts > 0:
    #     sleep(tts)
    # else:
    #     break
    # i += 1

i = 0
initial_time = time()
for tts_ in times_total[::-1]:
    i += 1
    print(f"{round(tts_, 3)} | {i}")
    sleep(tts_)
end_time = time()
print(f"Total time: {end_time-initial_time}")
# fall()


# plt.plot(times)
# plt.show()

'''
f(x) = y
y = 1/2a
x = sqrt(2*(y - z0)/9.81)
'''
