'''
DESCRIPTION:
    I am trying to simulate gravity in the terminal by
    calculating the time it takes for an
    object to fall 1 meter / character.

Generated by "sort.py"
'''

import math
from time import sleep

mass = 100
gravity = 9.81
lines_per_second = 0


def fall():
    i = 0
    time_to_sleep = 1
    while True:
        print("|          o          |")

        i += 1
        time_to_sleep = time_to_sleep/1.2

        sleep(time_to_sleep)


fall()
