'''
DESCRIPTION:
    Cool but useless

Generated by "sort.py"
'''

import random
from time import sleep

print("\n")
text = ""
char = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"


def rndmchar(length):
    while True:
        text = ""
        sleep(0.02)
        for i in range(length):
            text += random.choice(char)
            print(text, end="\r")


rndmchar(20)