'''
DESCRIPTION:
    This should decide things for me:
    I will give it for example "Go outside:5:3,Stay here:10:10".
    "Go outside" is the choice, :5:3 are the "why would i make this choice"
    (its good for my health = 5/10 pts, the weather is pretty good today = 3/10pts).
    Then, it will turn those numbers into ratios and choose a random number
    between 0 and 100. if the ratios are 30% and 70%, it will have a
    30% of landing on the first choice and 70% for the other.

Generated by "sort.py"
'''

print("choix:")
#choices = input().split(",")
choices = ["monter à Villars:3:8", "rester à Epalinges:9:4"]
values = []
values_int = [[], []]
values_sum = []
j = 0

for choice in choices:
    choice = choice.split(":")
    choice.pop(0)

    for i in choice:
        values_int[j].append(int(i))

    j += 1

for va in values_int:
    values_sum.append(sum(va))

n = percentages = []

for list in values_int:
    m = sum(list)
    percentages.append([round(100*i / m) for i in list])

print(percentages)
