'''
DESCRIPTION:
    Generates a noise pattern with ASCII characters in the console

Generated by "sort.py"
'''

from random import randint, choice, random
from math import sin

char_list = list(
    "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\|()1{}[]?-_+~<>i!lI;:,\"^`'.")
# char_list = list("abcdefghijklmnopqrstuvwxyz")
lines_range = 20
lines_char = 20
randomness = 2
range_random = list(range(-randomness, randomness))
del range_random[randomness]


def print_line():
    final = ""
    random = last_random = choice(range_random)/20
    print(random)

    for _ in range(60):
        randomn = choice(range_random)/10
        random = last_random + (choice(range_random)/10)
        last_random = random
        random = random * 10

        try:
            print(1/random)
        except ZeroDivisionError:
            return print("error", randomn, random)

        # char =  char_list[int(1/random*len(char_list))]
        # final += char

    return final

def print_square():
    for i in range(25):
        for i in range(50):
            random_number = choice(range(len(char_list)))
            last_random_number = random_number
            random_char = char_list[random_number]

            print(choice(random_char), end="")
        print()


print_square()
