'''
DESCRIPTION:
    Get some statistics on files (word and line count).

Generated by "sort.py"
'''

import os

asked_file = input("file: ")

if os.path.exists(asked_file):
    file = open(asked_file, "r")
    characters = len(file.read())
    file = open(asked_file, "r")

    lines = file.readlines()
    len_lines = len(lines)

    lines_strip = 0

    for line in lines:
        if line.rstrip():
            lines_strip += 1

    print("characters: "+str(characters) + "\nlines: " +
          str(len_lines)+" \nwithout empty lines: "+str(lines_strip))
else:
    print('file "'+asked_file+'" doesn\'t exist!')
