'''
DESCRIPTION:
    The popular FizzBuzz coding challenge

Generated by "sort.py"
'''


def fizz_buzz(num):
    what = ""

    if round(num/3) == num/3:
        what += "Fizz"
    if round(num/5) == num/5:
        what += "Buzz"
    if not len(what):
        what = str(num)

    return what


for i in range(49):
    print(fizz_buzz(i+1))
