'''
DESCRIPTION:
    Print a wave in the console with sine (or cosine or tangent)

Generated by "sort.py"
'''

from math import sin, cos, tan
from time import sleep

i = 0
j = 0.02
integer = ""
spaces = " "

while True:
    wave = 100
    if j < 0.1:
        j += 0.0003
    i += 0.05
    le = " " * wave
    cosinus = round(sin(i)*wave, 2)

    if abs(cosinus) == cosinus and int(cosinus) != 0:
        le += spaces*(int(cosinus))
        integer = "1"

    elif abs(cosinus) != cosinus and int(cosinus) != 0:
        le = le[:-len(spaces*(int(-cosinus)))]
        integer = "-1"

    elif int(cosinus) == 0:
        le = " "*wave
        integer = "0"

    towrite = "."+le+"o"
    print(le + integer)

    sleep(0.01)
